[project]
name = "gradecv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "bcrypt<4.0.0",
    "black>=26.5.1",
    "celery>=5.6.3",
    "fastapi[standard]>=0.141.1",
    "flake8>=7.3.0",
    "httpx>=0.28.1",
    "isort>=8.0.1",
    "numpy>=2.5.1",
    "openai>=2.52.0",
    "pandas>=3.0.5",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.14.2",
    "pymupdf>=1.28.0",
    "pypdf3>=1.0.6",
    "pytest>=9.1.1",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.51",
    "sqlmodel>=0.0.39",
    "streamlit>=1.60.0",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "pytest-asyncio>=1.4.0",
]
